### ISSUE TITLE
US02 - Eu, como usuário (a), desejo ser capaz de selecionar mais de uma váriavel, para que eu possa comparar os valores entre elas.

### ISSUE THREAD

**Issue by brunocmo** [fga-eps-mds/2022-1-Visualeasy-Doc#19]
**Descrição**

Permitir a seleção de múltiplas variáveis para poder criar um gráfico.

**Screenshots**

![US01 Screenshot](https://user-images.githubusercontent.com/48698728/181389897-2f67b928-55b2-474d-8c01-d16a034a73c2.png)

**Tarefas**

- [x] Buscar variáveis no Banco de Dados - [Issue #6](https://github.com/fga-eps-mds/2022-1-Visualeasy-Controle/issues/6);
- [x] Permitir a seleção de variáveis - [Issue #41](https://github.com/fga-eps-mds/2022-1-Visualeasy-Frontend/issues/41);
- [x] Salvar variáveis selecionadas no Backend - [Issue #7](https://github.com/fga-eps-mds/2022-1-Visualeasy-Controle/issues/7).

**Critérios de aceitação**

- [x] Uma variável pode ser selecionada com o mouse;
- [x] Múltiplas variáveis podem ser selecionadas no total;
- [x] Todas as tarefas cumpridas;
- [x] Cobertura de testes em pelo menos 80%.

**Comment by estevaoreis25** [comment]
Issues pertencentes à US02 foram fechadas
